create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text unique,display_name text,bio text default '',avatar_url text,created_at timestamptz default now());
create table if not exists public.prompts(id text primary key,title text not null,category text not null,model text not null,prompt_text text not null,preview_image text not null,aspect_ratio text default '1:1',created_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.generations(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,prompt_id text references public.prompts(id),model text not null,prompt_text text not null,reference_image text,output_image text,status text default 'completed',created_at timestamptz default now());
create table if not exists public.posts(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,generation_id uuid references public.generations(id) on delete set null,caption text default '',show_prompt boolean default true,allow_remix boolean default true,created_at timestamptz default now());

alter table public.profiles enable row level security;alter table public.prompts enable row level security;alter table public.generations enable row level security;alter table public.posts enable row level security;
create policy "public profiles" on public.profiles for select using(true);create policy "users update own profile" on public.profiles for update using(auth.uid()=id);create policy "public prompts" on public.prompts for select using(true);create policy "users read own generations" on public.generations for select using(auth.uid()=user_id);create policy "users create generations" on public.generations for insert with check(auth.uid()=user_id);create policy "public posts" on public.posts for select using(true);create policy "users create posts" on public.posts for insert with check(auth.uid()=user_id);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,username,display_name) values(new.id,split_part(new.email,'@',1),coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1))) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
